name: 'Run Tests'

on:
  release:
    types: 
      - 'published'
      - 'edited'

jobs:
  main:
    name: 'Run'
    uses: 'usf-cs272-spring2024/cs272-bot/.github/workflows/run-project.yml@main'
    secrets: 'inherit'
    permissions: 'write-all'
